### PR TITLE
Romna numeral

### PR DESCRIPTION
**Pull request by Hasinarahman**
Creating a Roman numeral converter by using html, css and js .

converter

### CODE REVIEW

**Comment by Hasinarahman** [comment]
Hi @Najeeba-Qarqin
please review my project.

**Comment by Najeeba-Qarqin** [comment]
@Hasinarahman well done great job 👍

- your project functionality is perfect. 
- your project passes the free code camp test. 
- Your codes are clean.
- You followed GitHub workflows. 
- your project have professional Readme file.
- The design you implemented is beautiful. 
- PR message is descriptive. 
- descriptive commit messages. 
Your project is done and you can mention the mentor.

**Comment by Hasinarahman** [comment]
@Najeeba-Qarqin 
Thank you dear.

**Comment by Hasinarahman** [comment]
@ahzamir 
Hello sir please check my project.

**Review by ahzamir — CHANGES_REQUESTED** [review]
@Hasinarahman 
- Well done you have done a great job by implementing many requirements but still your design is not responsive.

image

**Comment by Hasinarahman** [comment]
Hello sir @ahzamir
thank you for feedback I solve the problem please review again my project.

**Comment by Hasinarahman** [comment]
@ahzamir 
please check my project.

**Comment by ahzamir** [comment]
> @ahzamir please check my project.

- @Hasinarahman 

- You have not solved the problem of responsive yet.

**Comment by Hasinarahman** [comment]
Hi sir @ahzamir 
please check again for responsive the page.  in my computer it is responsive.

**Review by ahzamir — APPROVED** [review]
### Hi @Hasinarahman 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Roman Numeral Converter project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by Hasinarahman** [comment]
Ok thanks sir @ahzamir

**Pull request merged**
